import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {filterEvents,monthlyCounts} from './model.mjs';

const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_CORE || 'playwright-core');
const root = fileURLToPath(new URL('.',import.meta.url));
const output = process.env.REVIEW_DIR || resolve(root,'.impeccable/review');
await mkdir(output,{recursive:true});
const data = JSON.parse(await readFile(resolve(root,'data/archive.json'),'utf8'));
const url = process.env.HISTORY_URL || 'http://127.0.0.1:8765/';
const browser = await chromium.launch({executablePath:process.env.BROWSER_PATH || '/usr/bin/brave-browser',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page = await context.newPage();
const errors = [];
page.on('pageerror',error => errors.push(error.message));
try {
  await page.goto(url);
  await page.waitForSelector('#workspace:not([hidden])');
  await page.waitForFunction(() => document.getElementById('connection').textContent.includes('Offline ready'),{timeout:60000});
  assert.equal(await page.locator('.heatmap .year-head').count(),14);
  assert.equal(await page.locator('.heatmap .heat-cell').count(),168);
  assert.equal(await page.locator('[data-cell="2026,10"]').isDisabled(),true);
  const counts = monthlyCounts(filterEvents(data.events,{category:'picks'}),'picks');
  assert.equal(Number((await page.locator('[data-cell="2025,6"]').innerText()).replaceAll(',','')),counts.get('2025-07')||0);
  await page.screenshot({path:resolve(output,'desktop.png'),fullPage:true});
  await page.locator('[data-cell="2025,6"]').click();
  const july = filterEvents(data.events,{category:'picks',year:2025,month:6,day:null},true);
  assert((await page.locator('#ledger h2').innerText()).includes(july.length.toLocaleString()));
  assert.equal(await page.locator('.day-grid button').count(),31);
  await page.locator('[data-day="14"]').click();
  const daily = filterEvents(data.events,{category:'picks',year:2025,month:6,day:14},true);
  assert((await page.locator('#ledger h2').innerText()).includes(daily.length.toLocaleString()));
  await page.locator('#clear-period').click();
  await page.locator('[data-month-column="6"]').click();
  assert((await page.locator('#ledger h2').innerText()).includes('all years'));
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  assert.equal(download.suggestedFilename(),'legacy-nfl-calendar-events.csv');
  await download.saveAs(resolve(output,'filtered-events.csv'));
  await page.locator('#reset').click();
  await page.locator('#team').selectOption('0025');
  const teamEvents = filterEvents(data.events,{category:'picks',team:'0025'});
  const january = monthlyCounts(teamEvents,'picks').get('2025-01')||0;
  assert.equal(Number((await page.locator('[data-cell="2025,0"]').innerText()).replaceAll(',','')),january);
  await page.locator('nav a[href="#teams"]').click();
  await page.waitForSelector('#roster-year');
  assert((await page.locator('.entity-heading').innerText()).includes('Arizona'));
  await page.locator('#roster-year').selectOption('2014');
  await page.locator('#reset').click();
  await page.locator('nav a[href="#players"]').click();
  await page.locator('#player').fill('13589');
  await page.locator('#player').dispatchEvent('change');
  assert((await page.locator('.entity-heading').innerText()).includes('Josh Allen'));
  assert((await page.locator('#view').innerText()).includes('MFL ID 13589'));
  await page.screenshot({path:resolve(output,'player-desktop.png'),fullPage:true});
  await page.locator('#reset').click();
  await page.locator('nav a[href="#league"]').click();
  await page.locator('#season').selectOption('2025');
  assert((await page.locator('#view').innerText()).includes('Buffalo Bills'));
  await page.locator('nav a[href="#archive"]').click();
  await page.locator('#health').selectOption('error');
  assert((await page.locator('#view').innerText()).includes('97 matching files'));
  await page.locator('#archive-query').fill('2013');
  assert((await page.locator('#view').innerText()).includes('raw/2013/'));
  await page.locator('#reset').click();
  await page.locator('nav a[href="#calendar"]').click();
  await page.locator('#category').selectOption('assets');
  assert.equal(Number((await page.locator('[data-cell="2025,6"]').innerText()).replaceAll(',','')),monthlyCounts(filterEvents(data.events,{category:'assets'}),'assets').get('2025-07')||0);
  for (const category of ['trades','draft','waiver','roster','proposals','notes','all']) {
    await page.locator('#category').selectOption(category);
    assert((await page.locator('.chart-top h2').innerText()).includes('calendar year'));
  }
  await page.locator('#reset').click();
  const documentWidth = await page.evaluate(() => document.documentElement.scrollWidth);
  assert(documentWidth <= 1440,`desktop overflow ${documentWidth}`);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:resolve(output,'mobile.png'),fullPage:true});
  const mobileWidth = await page.evaluate(() => document.documentElement.scrollWidth);
  assert(mobileWidth <= 390,`mobile overflow ${mobileWidth}`);
  await context.setOffline(true);
  await page.reload();
  await page.waitForSelector('#workspace:not([hidden])');
  assert.equal(await page.locator('.heatmap .heat-cell').count(),168);
  await page.locator('nav a[href="#league"]').click();
  assert(await page.locator('#season').isVisible());
  await page.locator('nav a[href="#archive"]').click();
  assert((await page.locator('#view').innerText()).includes('1,705'));
  await context.setOffline(false);
  for (const path of ['/build_archive.py','/README.md','/raw/2025/league.json','/.git/config']) {
    assert.equal((await context.request.get(new URL(path,url).href)).status(),404);
  }
  assert.deepEqual(errors,[]);
  console.log('PASS: desktop/mobile, 168 heat cells, daily/month filters, team/player history, all activities, CSV, source inventory, source denial and full-index offline reload.');
} finally {await browser.close();}
