import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
import {DEFAULTS,monthlyGrid,summarize} from './behavior.mjs';
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_CORE || 'playwright-core');
const root = fileURLToPath(new URL('.',import.meta.url));
const output = process.env.REVIEW_DIR || resolve(root,'.impeccable/review');
await mkdir(output,{recursive:true});
const data = JSON.parse(await readFile(resolve(root,'data/archive.json'),'utf8'));
const url = process.env.HISTORY_URL || 'http://127.0.0.1:8765/';
const browser = await chromium.launch({executablePath:process.env.BROWSER_PATH || '/usr/bin/brave-browser',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page = await context.newPage(), errors = [];
page.on('pageerror',error => errors.push(error.message));
const numeric = async selector => Number((await page.locator(selector).innerText()).replaceAll(',',''));
const route = name => page.locator(`nav a[href="#${name}"]`).click();
const advanced = async () => {if (!await page.locator('#advanced').evaluate(e => e.open)) await page.locator('#advanced summary').click();};
const lens = patch => ({...DEFAULTS,...patch});
try {
  // Independent raw-inventory invariants (not just UI vs its own aggregator).
  assert.equal(data.schema,2);
  assert.equal(data.events.filter(e => e.type === 'TRADE').length,2634);
  assert.equal(data.events.filter(e => e.type === 'TRADE').reduce((n,e) => n+e.picks,0),3780);
  assert.equal(data.behavior.weeks.length,5590);
  assert.equal(data.behavior.weeks.filter(w => w.gap !== null).length,4215);
  assert.equal(data.behavior.coverage.find(r => r.season === 2026).unscoredRows,320);
  for (const week of data.behavior.weeks.filter(w => w.gap !== null)) {
    const points = new Map(week.points);
    assert(Math.abs(week.score-week.starters.reduce((n,p) => n+points.get(p),0)-week.adjustment) <= .02);
    assert(Math.abs(week.optimal-week.optimalPlayers.reduce((n,p) => n+points.get(p),0)-week.adjustment) <= .02);
    assert.equal(week.flags.length,0); assert(week.gap >= -.02);
  }
  await page.goto(url);
  await page.waitForSelector('#workspace:not([hidden])');
  await page.waitForFunction(() => document.getElementById('connection').textContent.includes('Offline ready'),{timeout:60000});
  assert.equal(await page.locator('.heatmap .year-head').count(),14);
  assert.equal(await page.locator('.heatmap .heat-cell').count(),168);
  assert(await page.locator('[data-cell="2026,10"]').isDisabled());
  assert.equal(await numeric('[data-cell="2025,6"]'),monthlyGrid(data,lens({})).get('2025-07'));
  await page.screenshot({path:resolve(output,'desktop.png'),fullPage:false});
  await advanced(); assert(await page.locator('#result').isDisabled()); assert(await page.locator('#role').isDisabled());
  await page.locator('#advanced summary').click();
  await page.locator('#policy').selectOption('all');
  await page.locator('[data-cell="2017,2"]').click();
  assert((await page.locator('#ledger h2').innerText()).includes('143 records'));
  assert.equal(await page.locator('.day-grid button').count(),31);
  await page.locator('#policy').selectOption('bilateral');
  assert.equal(await numeric('[data-cell="2017,2"]'),10);
  assert((await page.locator('#ledger h2').innerText()).includes('10 records'));
  await page.locator('#clear-period').click();
  await page.locator('#measure').selectOption('picks-in');
  assert.equal(await page.locator('[data-cell="2013,2"]').innerText(),'—');
  await page.locator('[data-cell="2013,2"]').click();
  assert((await page.locator('.day-grid [data-day="5"]').innerText()).includes('—'));
  await page.locator('#reset').click();
  await page.locator('#team').focus();
  await page.locator('#team').selectOption('0025');
  assert.equal(await page.evaluate(() => document.activeElement.id),'team','filter repaint preserves keyboard focus');
  await page.locator('#compare').selectOption('0001');
  await advanced();
  await page.locator('#asset').selectOption('pick');
  await page.locator('#round').selectOption('1');
  await page.locator('#direction').selectOption('in');
  await page.locator('#measure').selectOption('picks-in');
  await page.locator('[data-cell="2025,6"]').click();
  assert.equal(await page.locator('#export').isDisabled(),true,'empty selection cannot export invented receipts');
  assert((await page.locator('#ledger').innerText()).includes('No qualifying records'));
  const state = lens({team:'0025',compare:'0001',asset:'pick',round:'1',direction:'in',measure:'picks-in',year:2024,month:2});
  assert.equal(await numeric('[data-cell="2024,2"]'),monthlyGrid(data,state).get('2024-03'));
  await page.locator('[data-cell="2024,2"]').click();
  const report = summarize(data,state);
  assert(report.views.length > 0);
  assert((await page.locator('#ledger h2').innerText()).includes(`${report.views.length} records`));
  assert((await page.locator('.norm-readout').innerText()).includes(`${report.pin} picks received`));
  let promise = page.waitForEvent('download'); await page.locator('#export').click();
  let download = await promise; assert.equal(download.suggestedFilename(),'legacy-nfl-calendar-events.csv');
  await download.saveAs(resolve(output,'filtered-events.csv'));
  assert((await readFile(resolve(output,'filtered-events.csv'),'utf8')).includes('Assets received'));
  promise = page.waitForEvent('download'); await page.locator('#export-findings').click(); download = await promise;
  await download.saveAs(resolve(output,'behavior-findings.json'));
  const findings = JSON.parse(await readFile(resolve(output,'behavior-findings.json'),'utf8'));
  assert.equal(findings.context.round,'1'); assert.equal(findings.counts.pickDenominator,report.pickDenominator);
  assert.equal(findings.receipts.length,report.views.length); assert.equal(findings.subject.verifiedOwner,false);
  assert(findings.receipts[0].sources[0].file.startsWith('raw/'));
  assert.equal(findings.peers.length,32);
  assert.equal(findings.indexRevision,JSON.parse(await readFile(resolve(root,'data/revision.json'),'utf8')).revision);
  await route('compare');
  assert((await page.locator('#view').innerText()).includes('Arizona Cardinals vs. Buffalo Bills'));
  assert.equal(await page.locator('#view table').nth(1).locator('tbody tr').count(),32);
  await route('teams');
  assert((await page.locator('.entity-heading').innerText()).includes('Arizona'));
  assert((await page.locator('#view').innerText()).includes('Counterpart concentration'));
  assert((await page.locator('#view').innerText()).includes('Earlier eligible years'));
  assert((await page.locator('#entity-status').innerText()).includes('Mar 2024'));
  await page.screenshot({path:resolve(output,'dossier.png'),fullPage:false});
  // Saved context survives reload, and saved-lens deletion really works.
  await page.locator('#questions summary').click();
  await page.locator('#question-name').fill('First-round receipts');
  await page.locator('#question-save').click();
  assert.equal(await page.locator('#question').inputValue(),'saved-0');
  await page.reload(); await page.waitForSelector('#workspace:not([hidden])');
  await page.locator('#questions summary').click(); await page.locator('#question').selectOption('saved-0');
  assert.equal(await page.locator('#round').inputValue(),'1');
  await page.locator('#question-delete').click();
  assert.equal(await page.locator('#question option[value="saved-0"]').count(),0);
  await page.locator('#reset').click();
  await route('weekly');
  assert((await page.locator('#view').innerText()).includes('4215 / 5590'));
  assert((await page.locator('#view').innerText()).includes('2014/2015 home bonuses'));
  await page.locator('#team').selectOption('0025');
  assert((await page.locator('#view').innerText()).includes('Trade receipt → observed usage'));
  await page.screenshot({path:resolve(output,'weekly.png'),fullPage:false});
  promise = page.waitForEvent('download'); await page.locator('#export-findings').click(); download = await promise;
  await download.saveAs(resolve(output,'weekly-findings.json'));
  const weeklyFindings = JSON.parse(await readFile(resolve(output,'weekly-findings.json'),'utf8'));
  assert(weeklyFindings.weeklyReport.eligibleWeeks > 0);
  assert(weeklyFindings.weeklyReport.receipts[0].sources[0].file.startsWith('raw/'));
  await route('teams');
  await page.locator('summary:has-text("Reported roster states")').click();
  await page.locator('#roster-year').selectOption('2014');
  await page.locator('#reset').click(); await route('players');
  await page.locator('#player').fill('13589'); await page.locator('#player').dispatchEvent('change');
  assert((await page.locator('.entity-heading').innerText()).includes('Josh Allen'));
  assert((await page.locator('#view').innerText()).includes('MFL ID 13589'));
  await page.locator('#category').selectOption('all');
  assert((await page.locator('#ledger').innerText()).includes('DRAFT'));
  await page.locator('#reset').click(); await route('league');
  await page.locator('#season').selectOption('2025');
  assert((await page.locator('#view').innerText()).includes('Buffalo Bills'));
  await route('archive'); await page.locator('#health').selectOption('error');
  assert((await page.locator('#view').innerText()).includes('97 matching files'));
  await page.locator('#archive-query').fill('2013');
  assert((await page.locator('#view').innerText()).includes('raw/2013/'));
  await page.locator('#reset').click(); await route('calendar');
  for (const channel of ['draft','adds','manual','status','proposals','all','trade']) {
    await page.locator('#category').selectOption(channel);
    assert.equal(await page.locator('#measure').isDisabled(),channel !== 'trade');
  }
  await page.locator('#category').selectOption('manual'); await route('compare');
  assert(await page.locator('#trade-analysis').isVisible()); await page.locator('#trade-analysis').click();
  assert.equal(await page.locator('#category').inputValue(),'trade');
  await route('calendar');
  await page.locator('#team').selectOption('0025'); await advanced();
  await page.locator('#asset').selectOption('player'); await page.locator('#position').selectOption('QB');
  await page.locator('#measure').selectOption('players-in');
  assert((await page.locator('.norm-readout').innerText()).includes('Player-receiving share'));
  await route('compare'); assert((await page.locator('#view').innerText()).includes('Players received / sent'));
  await route('calendar'); await page.locator('#measure').selectOption('picks-in');
  assert(await page.locator('#clear-asset-facets').isVisible()); await page.locator('#clear-asset-facets').click();
  await page.locator('#reset').click(); await page.locator('[data-month-column="6"]').click();
  assert((await page.locator('#entity-status').innerText()).includes('across all years'));
  await page.locator('#reset').click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth) <= 1440);
  await page.setViewportSize({width:390,height:844});
  for (const name of ['calendar','compare','teams','weekly','league','players','archive']) {
    await route(name); assert(await page.evaluate(() => document.documentElement.scrollWidth) <= 390,`${name} mobile overflow`);
  }
  await route('calendar');
  for (const id of ['questions','advanced']) if (await page.locator('#'+id).evaluate(el => el.open)) await page.locator('#'+id+' summary').click();
  await page.screenshot({path:resolve(output,'mobile.png'),fullPage:false});
  await context.setOffline(true); await page.reload(); await page.waitForSelector('#workspace:not([hidden])');
  assert.equal(await page.locator('.heatmap .heat-cell').count(),168);
  for (const name of ['compare','teams','weekly','league','players','archive']) {await route(name); assert(await page.locator('#view').isVisible());}
  await context.setOffline(false);
  assert.equal((await context.request.get(url,{headers:{Host:'attacker.example:8765'}})).status(),403);
  for (const path of ['/build_archive.py','/behavior_archive.py','/README.md','/data/tenures.json','/raw/2025/league.json','/.git/config','/%2e%2e/league-archive/manifest.jsonl']) assert.equal((await context.request.get(new URL(path,url).href)).status(),404);
  await page.goto(url+'#constructor?player=__proto__&from=2026-99-99');
  await page.waitForSelector('#workspace:not([hidden])'); assert.equal(await page.locator('#team').inputValue(),'');
  assert.deepEqual(errors,[]);
  console.log('PASS: raw invariants, 168 cells, unknown ≠ zero, 143→10 ambiguous-policy audit, directed facets/denominators, same-context peers, dossier, reconciliation, usage/censoring, sources, saved lenses, keyboard focus, CSV/JSON, all channels, 1440/390px, full offline reload and source denial.');
} finally {await browser.close();}
