import {playerLabel} from './model.mjs';
import {selection,facetMatch,summarize} from './behavior.mjs';
import {receipts,metricReadiness} from './behavior_views.mjs';
export function renderLeague(c) {
  const {data,state:s,fmt,escape:e,table,teamLink,sourceDetails} = c;
  const year = Number(s.season || s.year || data.years.at(-2)), season = data.seasons.find(row => row.year === year);
  const summaries = data.seasons.map(row => {
    const events = summarize(data,{...s,year:row.year}).views;
    return `<tr><td><button class="text-button" data-season="${row.year}">${row.year}</button></td><td>${row.champion ? teamLink(row.champion.team,row.year) : 'Not recorded / undecided'}</td><td class="numeric">${fmt(events.length)}</td><td class="numeric">${fmt(events.reduce((n,v) => n+v.event.picks,0))}</td></tr>`;
  });
  const standings = season.standings.filter(row => !s.team || row.team === s.team).sort((a,b) => (b.wins||0)-(a.wins||0) || (b.pf||0)-(a.pf||0));
  let html = `<p class="history-note">Activity uses current filters by calendar year; this trajectory clears only the clicked year; the month/day slice remains. Champions and standings are whole-source-season outcomes, not filtered events or causal judgments. Newest year is partial.</p>${table(['Year','Recorded Super Bowl winner','Qualifying activity','Encoded picks moved'],summaries)}<label class="season-tool">Results source season<select id="season">${data.years.map(y => `<option ${y === year ? 'selected' : ''}>${y}</option>`).join('')}</select></label><h2>Reported standings · ${year}</h2><p class="history-note">Ordered by wins, then points, not the complete MFL tie-breaker. YTD points may include playoffs.</p>${table(['Franchise','W–L–T','Points for (YTD)','Points against','All-play %','Evidence'],standings.map(row => `<tr><td>${teamLink(row.team,year)}</td><td>${row.wins}–${row.losses}–${row.ties}</td><td class="numeric">${fmt(row.pf,2)}</td><td class="numeric">${fmt(row.pa,2)}</td><td class="numeric">${row.allPlay === null ? 'Unavailable' : fmt(row.allPlay*100,1)+'%'}</td><td>${sourceDetails([row.source])}</td></tr>`))}`;
  const draft = selection(data,{...s,category:'draft',year:null,month:null,day:null,phase:'',shape:'',result:'',role:''}).filter(v => v.event.season === year && facetMatch(v,s));
  html += `<h2>Recorded draft · ${year}</h2><p class="history-note">Draft selections in the chosen source season, with franchise/player/date/tenure filters. Trade-only context facets do not apply.</p>`+receipts({...c,state:{...s,category:'draft'}},draft);
  return html;
}
export function renderPlayers(c) {
  const {data,state:s,fmt,escape:e,table,playerLink,teamLink,sourceDetails,playerName} = c;
  if (!s.player) {
    const query = (s.query||'').trim().toLowerCase();
    const candidates = Object.values(data.players).filter(p => (!query || playerLabel(p).toLowerCase().includes(query)) && (!s.team || data.snapshots[p.id]?.some(row => row.team === s.team)) && (query || data.snapshots[p.id]));
    return `<p>Choose a player suggestion above, or open one below. ${fmt(candidates.length)} matches; first 60 shown.</p>${table(['Player','MFL ID','Latest listed position','Latest listed NFL team'],candidates.slice(0,60).map(p => `<tr><td>${playerLink(p.id)}</td><td>${e(p.id)}</td><td>${e(p.position)}</td><td>${e(p.team)}</td></tr>`))}`;
  }
  const player = data.players[s.player], observations = (data.snapshots[s.player]||[]).filter(row => !s.team || row.team === s.team).sort((a,b) => b.season-a.season);
  const scores = [...(data.scores[s.player]||[])].sort((a,b) => b.season-a.season);
  const views = selection(data,s).filter(v => facetMatch(v,s));
  return `<h2 class="entity-heading">${e(playerName(s.player))}</h2><p class="history-note">MFL ID ${e(s.player)} · latest listed position ${e(player.position)} · latest NFL team ${e(player.team)}. Player attributes here are directory observations, not historical valuations or dated ages.</p><h3>Season scoring</h3><p class="history-note">MFL YTD totals, player-wide; newest season partial. Missing rows are unavailable, not zero. Snapshot and YTD tables are source-season browse context; they are not constrained by event-time facets.</p>${table(['Source season','YTD league points','Evidence'],scores.map(row => `<tr><td>${row.season}</td><td class="numeric">${fmt(row.score,2)}</td><td>${sourceDetails([row.source])}</td></tr>`))}<h3>Reported roster states</h3><p class="history-note">Grouped week observations, not continuous custody. Changes in salary, status or contract create distinct states.</p>${table(['Season','Franchise','Status','Salary (league units)','Contract year','Observed weeks','Evidence'],observations.map(row => `<tr><td>${row.season}</td><td>${teamLink(row.team,row.season)}</td><td>${e(row.status)}</td><td>${fmt(row.salary,2)}</td><td>${e(row.contract||'Unavailable')}</td><td class="wrap">${row.weeks.map(w => w ?? 'unspecified').join(', ')}</td><td>${sourceDetails(row.sources)}</td></tr>`))}<h2>Matching player events</h2><p class="history-note">Shared filters apply. Select “All archived events” to include the draft and manual/free-agent movements, not just trades.</p>${receipts(c,views)}`;
}
export function renderArchive(c) {
  const {data,state:s,fmt,escape:e,table} = c;
  const query = (s.archiveQuery||'').toLowerCase(), files = data.files.filter(row => (!s.health || s.health === row.health) && (!query || `${row.file} ${row.type} ${row.status}`.toLowerCase().includes(query)));
  const start = s.page*40;
  return `${metricReadiness(c)}<section><h2>Source inventory</h2><p>${fmt(data.files.length)} files; ${fmt(data.counts.ok)} usable responses; ${fmt(data.counts.error)} expected MFL errors; ${fmt(data.counts.empty)} empty responses. Inventory ignores subject/event filters.</p><div class="inline-tools"><label>Find a source<input id="archive-query" type="search" value="${e(s.archiveQuery)}" placeholder="Year, file or data type"></label><label>Status<select id="health">${[['','All statuses'],['ok','Usable'],['error','MFL error'],['empty','Empty']].map(([value,label]) => `<option value="${value}" ${s.health === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label></div><p class="muted">${fmt(files.length)} matching files</p>${table(['Source season','File','Type','Status','Size','Detail'],files.slice(start,start+40).map(row => `<tr><td>${row.year}</td><td class="file-path"><code>${e(row.file)}</code></td><td>${e(row.type)}</td><td>${e(row.health)}</td><td>${fmt(row.bytes/1024,1)} KB</td><td class="wrap">${e(row.status)}</td></tr>`))}<div class="pagination"><button data-page="-1" ${s.page === 0 ? 'disabled' : ''}>Previous</button><span>${files.length ? start+1 : 0}–${Math.min(start+40,files.length)} of ${fmt(files.length)}</span><button data-page="1" ${start+40 >= files.length ? 'disabled' : ''}>Next</button></div><h3>Provenance, privacy and offline use</h3><ul><li>Transaction/draft record numbers are one-based indices into source arrays. Weekly receipts name week, block, matchup and franchise. Indexed records are normalized, not verbatim source JSON.</li><li>Identical dated transactions are deduplicated while preserving all source references. Undated records cannot be safely deduplicated across seasons.</li><li>Proposal/status notices never count as completed trades. LOAD_ROSTERS movements are retained and flagged as manual adjustments, not freely attributed to a GM.</li><li>Owner contacts, credentials, messages and arbitrary trade comments are not exposed. Draft pick notes remain. The allowlist server denies raw files and source code.</li><li>Local archive only; no live MFL requests and no league/database writes. The generated index and any tenure mapping stay local, out of git.</li><li>Open on localhost or private HTTPS and wait for “Offline ready” before disconnecting. Plain LAN HTTP is online-only. Saved questions live only in this browser; exports contain private league observations.</li></ul></section>`;
}
