package fit

import (
	"fmt"
	"math"
	"strings"
)

// Markdown renders the fit report: what was fitted, on what, and how each fit scored on the
// holdout season.
func Markdown(results []Result, first, holdout int, source string) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	w("# Fit report\n\nGenerated by `go run ./cmd/fit` from %s. Seasons %d–%d; every fit is trained on "+
		"seasons before %d and scored on predicting %d, then refitted on all seasons for the stored values.\n\n",
		source, first, holdout, holdout, holdout)
	w("The scale is a within-position percentile of league fantasy points per game played, among the "+
		"season's regulars (%d+ games). RMSE is in percentile points unless marked.\n\n", 4)

	w("## On-field-now k (within-season reliability)\n\n")
	w("| Pos | Seasons | k vs mean (games) | Prior R² true | k vs prior | Split-half n | RMSE odd→even raw | shrunk | mean (pts/game) |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		w("| %s | %d | %s | %s | %s | %d | %s | %s | %s |\n", r.Position, r.Report.Seasons, f1(r.Report.KNow),
			f2(r.Report.PriorR2True), f1(r.Params.KNow), r.Report.SplitN, f2(r.Report.SplitRaw), f2(r.Report.SplitShrunk), f2(r.Report.SplitMean))
	}
	w("\n## Prior (joint regression on draft, entry age, combine, college)\n\n")
	w("| Pos | Train n | R² train | Holdout n | R² holdout |\n|---|---|---|---|---|\n")
	for _, r := range results {
		w("| %s | %d | %s | %d | %s |\n", r.Position, r.Report.PriorN, f2(r.Report.PriorR2), r.Report.PriorTestN, f2(r.Report.PriorR2Test))
	}
	w("\n## Dynasty k and the shape of Z (season pairs, shrinking toward the prior)\n\n")
	w("| Pos | Pairs train/holdout | k (games) | Shape kept | RMSE e/(e+k) | RMSE 1−exp(−e/k) | last season alone | prior alone |\n|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		shape := "e/(e+k)"
		if r.Params.Exponential {
			shape = "1−exp(−e/k)"
		}
		w("| %s | %d/%d | %s | %s | %s | %s | %s | %s |\n", r.Position, r.Report.PairsTrain, r.Report.PairsTest, f1(r.Params.KDynasty), shape,
			f3(r.Report.DynCredibility), f3(r.Report.DynExponential), f3(r.Report.DynLastSeason), f3(r.Report.DynPrior))
	}
	w("\n## Recency weights (after age adjustment)\n\n")
	w("| Pos | Train/holdout | Weights (latest, −1, −2) | RMSE fitted | RMSE Marcel 1/0.8/0.6 |\n|---|---|---|---|---|\n")
	for _, r := range results {
		w("| %s | %d/%d | 1 / %.1f / %.1f | %s | %s |\n", r.Position, r.Report.Recency.Train, r.Report.Recency.Test,
			r.Params.Recency[0], r.Params.Recency[1], f3(r.Report.Recency.RMSEFitted), f3(r.Report.Recency.RMSEMarc))
	}
	w("\n## Talent arc (fitted with the dynasty k on what the blend leaves; survivors weighted by 1/P(survive))\n\n")
	w("| Pos | Exits | Step at 23 | at 27 | at 31 | Second-year jump | RMSE with arc | without |\n|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		a := r.Report.Arc
		w("| %s | %d | %+.3f | %+.3f | %+.3f | %+.3f | %s | %s |\n", r.Position, a.Exits,
			r.Params.ArcStep(23, 3), r.Params.ArcStep(27, 3), r.Params.ArcStep(31, 3), r.Params.Arc[3], f3(a.RMSEArc), f3(a.RMSEFlat))
	}
	w("\n## Survival arc (plays next season)\n\n")
	w("| Pos | Train/holdout | Base rate | Holdout rate | Log loss fitted | Log loss base rate | P(plays) at 24 / 30 / 34, round-1 regular |\n|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		s := r.Report.Survival
		w("| %s | %d/%d | %s | %s | %s | %s | %s / %s / %s |\n", r.Position, s.Train, s.Test, f2(s.BaseRate), f2(s.HoldoutObserved),
			f3(s.LogLossFit), f3(s.LogLossBase), f2(r.Params.Survives(24, 16, 15, 0.6)), f2(r.Params.Survives(30, 16, 15, 0.6)), f2(r.Params.Survives(34, 16, 15, 0.6)))
	}
	w("\n## Limits\n\n" +
		"- No free source has IDP opportunity denominators (pass-rush snaps, routes, coverage snaps); IDP production is points per game.\n" +
		"- IDP arcs come from these five seasons only; no published IDP curve exists to check them against.\n" +
		"- nflverse's generic \"DB\" players are left out of the fit; their position is ambiguous between CB and S.\n" +
		"- The prior's weight for the app's own scouting history needs years of stored priors.\n")
	return b.String()
}

func f1(v float64) string { return num(v, "%.1f") }
func f2(v float64) string { return num(v, "%.2f") }
func f3(v float64) string { return num(v, "%.3f") }

func num(v float64, format string) string {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return "—"
	}
	return fmt.Sprintf(format, v)
}
