package fit

import (
	"fmt"
	"math"
	"strings"

	"github.com/secureprospective/TheWarRoom/internal/domain"
	"github.com/secureprospective/TheWarRoom/internal/model"
)

// Markdown renders the fit report: what was fitted, on what, and how each fit scored on the
// holdout season.
func Markdown(results []Result, checks []BoardCheck, first, holdout int, source string) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	w("# Fit report\n\nGenerated by `go run ./cmd/fit` from %s. Seasons %d–%d; every fit is trained on "+
		"seasons before %d and scored on predicting %d, then refitted on all seasons for the stored values. Every fitted piece "+
		"that has a simpler alternative (the arc vs none, recency weights vs Marcel's, the survival and debut models vs their base rates) is "+
		"kept only if it beats that alternative on the holdout.\n\n",
		source, first, holdout, holdout, holdout)
	w("The scale is a within-position percentile of league fantasy points per game played, among the "+
		"season's regulars (%d+ games). RMSE is in percentile points unless marked.\n\n", 4)

	w("## On-field-now k (within-season reliability)\n\n")
	w("| Pos | Seasons | k vs mean (games) | Prior R² true | k vs prior | Split-half n | RMSE odd→even raw | shrunk | mean (pts/game) |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		w("| %s | %d | %s | %s | %s | %d | %s | %s | %s |\n", r.Position, r.Report.Seasons, f1(r.Report.KNow),
			f2(r.Report.PriorR2True), f1(r.Params.KNow), r.Report.SplitN, f2(r.Report.SplitRaw), f2(r.Report.SplitShrunk), f2(r.Report.SplitMean))
	}
	w("\n## Prior (joint regression on draft, entry age, combine, college)\n\n")
	w("| Pos | Train n | R² train | Holdout n | R² holdout |\n|---|---|---|---|---|\n")
	for _, r := range results {
		w("| %s | %d | %s | %d | %s |\n", r.Position, r.Report.PriorN, f2(r.Report.PriorR2), r.Report.PriorTestN, f2(r.Report.PriorR2Test))
	}
	w("\n## Dynasty k and the shape of Z (season pairs, shrinking toward the prior)\n\n")
	w("| Pos | Pairs train/holdout | k (games) | Shape kept | RMSE e/(e+k) | RMSE 1−exp(−e/k) | last season alone | prior alone |\n|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		shape := "e/(e+k)"
		if r.Params.Exponential {
			shape = "1−exp(−e/k)"
		}
		w("| %s | %d/%d | %s | %s | %s | %s | %s | %s |\n", r.Position, r.Report.PairsTrain, r.Report.PairsTest, f1(r.Params.KDynasty), shape,
			f3(r.Report.DynCredibility), f3(r.Report.DynExponential), f3(r.Report.DynLastSeason), f3(r.Report.DynPrior))
	}
	w("\n## Recency weights (after age adjustment)\n\n")
	w("| Pos | Train/holdout | RMSE fitted | RMSE Marcel 1/0.8/0.6 | Kept | Stored weights (latest, −1, −2) |\n|---|---|---|---|---|---|\n")
	for _, r := range results {
		rc := r.Report.Recency
		w("| %s | %d/%d | %s | %s | %s | 1 / %.1f / %.1f |\n", r.Position, rc.Train, rc.Test, f3(rc.RMSEFitted), f3(rc.RMSEMarc),
			kept(rc.Kept, "fitted", "Marcel"), r.Params.Recency[0], r.Params.Recency[1])
	}
	w("\n## Talent arc (fitted with the dynasty k on what the blend leaves; survivors weighted by 1/P(survive))\n\n")
	w("| Pos | Exits | RMSE with arc | without | Kept | Stored step at 23 | at 27 | at 31 | Second-year jump |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		a := r.Report.Arc
		w("| %s | %d | %s | %s | %s | %+.3f | %+.3f | %+.3f | %+.3f |\n", r.Position, a.Exits, f3(a.RMSEArc), f3(a.RMSEFlat),
			kept(a.Kept, "arc", "none"), r.Params.ArcStep(23, 3), r.Params.ArcStep(27, 3), r.Params.ArcStep(31, 3), r.Params.Arc[3])
	}
	survivalSection(w, results)
	debutSection(w, results)
	boardSection(w, checks, holdout)
	limitsSection(w)
	return b.String()
}

// limitsSection lists what the fit cannot see.
func limitsSection(w func(string, ...any)) {
	w("\n## Limits\n\n" +
		"- IDP production is points per game. Opportunity shares from nflverse's participation data (2016–2025: pass-play and run-play snap shares, pressures per pass snap) and PFR's pass-rush and missed-tackle counts were tested on the 2023–2025 holdouts and did not predict the next season beyond this one's points (scouting research, 2026-10-04).\n" +
		"- IDP arcs come from these five seasons only; no published IDP curve exists to check them against.\n" +
		"- The holdout is one season. Kept/fallback choices decided by less than 0.002 are within its noise; the rule " +
		"still takes the lower number, and the simpler piece on a tie.\n" +
		"- Players are fitted at the position MFL lists them at; a player MFL does not list keeps nflverse's, and nflverse's generic \"DB\" among them is left out, its position ambiguous between CB and S.\n" +
		"- Kickers: a season barely predicts the next and the prior explains nothing, so the model shrinks toward a " +
		"prior that is noise and ranks kickers worse than last season's total does (see Against today's board).\n" +
		"- The prior's weight for the app's own scouting history needs years of stored priors.\n")
}

// survivalSection is the survival arc's holdout scores and stored chances.
func survivalSection(w func(string, ...any), results []Result) {
	w("\n## Survival arc (plays next season)\n\n")
	w("At DT, DE, LB, CB and S the regression also reads the NFL contract the player is on (OTC via nflverse: cap share, " +
		"years left, guaranteed share); it is kept only when it beats the same regression without it. The stored chances " +
		"below are for a player with no contract on file, which at those positions is mostly an unsigned or fringe player: " +
		"every 2025 defensive regular had one.\n\n")
	w("| Pos | Train/holdout | Base rate | Holdout rate | Log loss fitted | without contract | Contract | Log loss base rate | Kept | Stored P(plays) at 24 / 30 / 34, round-1 regular |\n|---|---|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		s := r.Report.Survival
		without, contract := "—", "—"
		if len(model.SurvivalTerms(r.Position)) > len(model.SurvivalTerms(domain.PosQB)) {
			without, contract = f3(s.LogLossNoContract), kept(s.Contract, "kept", "dropped")
		}
		plays := func(age float64) string { return f2(r.Params.Survives(age, 16, 15, 0.6, model.Tenure{})) }
		w("| %s | %d/%d | %s | %s | %s | %s | %s | %s | %s | %s / %s / %s |\n", r.Position, s.Train, s.Test, f2(s.BaseRate),
			f2(s.HoldoutObserved), f3(s.LogLossFit), without, contract, f3(s.LogLossBase), kept(s.Kept, "model", "base rate"),
			plays(24), plays(30), plays(34))
	}
}

// debutSection reports the chance a rookie becomes a regular in his first season.
func debutSection(w func(string, ...any), results []Result) {
	w("\n## Debut (a rookie becomes a regular, 4+ games, in his first season)\n\n")
	w("| Pos | Rookies train/holdout | Base rate | Holdout rate | Log loss fitted | Log loss base rate | Kept | Stored P at pick 1 / 32 / 100 / undrafted |\n|---|---|---|---|---|---|---|---|\n")
	for _, r := range results {
		d, p := r.Report.Debut, r.Params
		w("| %s | %d/%d | %s | %s | %s | %s | %s | %s / %s / %s / %s |\n", r.Position, d.Train, d.Test, f2(d.BaseRate),
			f2(d.HoldoutObserved), f3(d.LogLossFit), f3(d.LogLossBase), kept(d.Kept, "model", "base rate"),
			f2(p.Debuts(1)), f2(p.Debuts(32)), f2(p.Debuts(100)), f2(p.Debuts(0)))
	}
}

// boardSection compares the trained model with today's board on the holdout season.
func boardSection(w func(string, ...any), checks []BoardCheck, holdout int) {
	if len(checks) == 0 {
		return
	}
	w("\n## Against today's board (%d predicted from seasons before it)\n\n", holdout)
	w("Spearman rank correlation with what happened in %d. Today's board is last season's total league points "+
		"times the engine's age pull. **Talent:** the season's regulars, against points per game. **Value:** everyone "+
		"who played the season before, against the season's total points; the model's level is weighted by its "+
		"chance he plays. **Rookies:** today's board gives every rookie 0, so it has no ranking of them.\n\n", holdout)
	w("| Pos | Talent n | model | today | Value n | model | today | Rookie regulars | model |\n|---|---|---|---|---|---|---|---|---|\n")
	for _, c := range checks {
		w("| %s | %d | %s | %s | %d | %s | %s | %d | %s |\n", c.Position, c.TalentN, f2(c.TalentModel), f2(c.TalentToday),
			c.ValueN, f2(c.ValueModel), f2(c.ValueToday), c.RookieN, f2(c.RookieModel))
	}
}

func kept(fitted bool, yes, no string) string {
	if fitted {
		return yes
	}
	return no
}

func f1(v float64) string { return num(v, "%.1f") }
func f2(v float64) string { return num(v, "%.2f") }
func f3(v float64) string { return num(v, "%.3f") }

func num(v float64, format string) string {
	if math.IsNaN(v) || math.IsInf(v, 0) {
		return "—"
	}
	return fmt.Sprintf(format, v)
}
