// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function DeleteMFLKey() {
  return window['go']['main']['App']['DeleteMFLKey']();
}

export function ExecuteTransaction(arg1) {
  return window['go']['main']['App']['ExecuteTransaction'](arg1);
}

export function GetCalendarEvents() {
  return window['go']['main']['App']['GetCalendarEvents']();
}

export function GetCrosswalkReport() {
  return window['go']['main']['App']['GetCrosswalkReport']();
}

export function GetCurrentPhase() {
  return window['go']['main']['App']['GetCurrentPhase']();
}

export function GetFeed() {
  return window['go']['main']['App']['GetFeed']();
}

export function GetFranchises() {
  return window['go']['main']['App']['GetFranchises']();
}

export function GetFreeAgentPool() {
  return window['go']['main']['App']['GetFreeAgentPool']();
}

export function GetLeagueSchedule() {
  return window['go']['main']['App']['GetLeagueSchedule']();
}

export function GetLeagueSetting(arg1) {
  return window['go']['main']['App']['GetLeagueSetting'](arg1);
}

export function GetLegalOps() {
  return window['go']['main']['App']['GetLegalOps']();
}

export function GetParams() {
  return window['go']['main']['App']['GetParams']();
}

export function GetPlayerScore(arg1) {
  return window['go']['main']['App']['GetPlayerScore'](arg1);
}

export function GetPowerRankings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetPowerRankings'](arg1, arg2, arg3, arg4);
}

export function GetRankings() {
  return window['go']['main']['App']['GetRankings']();
}

export function GetRoster(arg1) {
  return window['go']['main']['App']['GetRoster'](arg1);
}

export function GetSignals() {
  return window['go']['main']['App']['GetSignals']();
}

export function LoadCrosswalk() {
  return window['go']['main']['App']['LoadCrosswalk']();
}

export function LoadSignals() {
  return window['go']['main']['App']['LoadSignals']();
}

export function MFLKeyStatus() {
  return window['go']['main']['App']['MFLKeyStatus']();
}

export function PreviewTransaction(arg1) {
  return window['go']['main']['App']['PreviewTransaction'](arg1);
}

export function RefreshLeague() {
  return window['go']['main']['App']['RefreshLeague']();
}

export function ResetParam(arg1, arg2) {
  return window['go']['main']['App']['ResetParam'](arg1, arg2);
}

export function ScoreLeague() {
  return window['go']['main']['App']['ScoreLeague']();
}

export function SetLeagueSettingOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetLeagueSettingOverride'](arg1, arg2, arg3);
}

export function SetMFLKey(arg1) {
  return window['go']['main']['App']['SetMFLKey'](arg1);
}

export function SetParam(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetParam'](arg1, arg2, arg3);
}

export function TargetCheckLineup(arg1, arg2) {
  return window['go']['main']['App']['TargetCheckLineup'](arg1, arg2);
}

export function TargetCheckMoves() {
  return window['go']['main']['App']['TargetCheckMoves']();
}

export function TargetClock() {
  return window['go']['main']['App']['TargetClock']();
}

export function TargetDraftIR(arg1, arg2) {
  return window['go']['main']['App']['TargetDraftIR'](arg1, arg2);
}

export function TargetDraftLineup(arg1, arg2) {
  return window['go']['main']['App']['TargetDraftLineup'](arg1, arg2);
}

export function TargetHandOff(arg1) {
  return window['go']['main']['App']['TargetHandOff'](arg1);
}

export function TargetLineup(arg1) {
  return window['go']['main']['App']['TargetLineup'](arg1);
}

export function TargetMoves(arg1) {
  return window['go']['main']['App']['TargetMoves'](arg1);
}

export function TargetSeason() {
  return window['go']['main']['App']['TargetSeason']();
}

export function TargetSnapshot() {
  return window['go']['main']['App']['TargetSnapshot']();
}
