// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteTransaction(arg1:main.TransactionRequest):Promise<main.TransactionResult>;

export function GetCurrentPhase():Promise<main.PhaseResult>;

export function GetFranchiseState(arg1:string):Promise<main.FranchiseStateResult>;

export function GetFreeAgents():Promise<main.FreeAgentsResult>;

export function GetParams():Promise<main.ParamsResult>;

export function GetRankings():Promise<main.RankingsResult>;

export function Ping():Promise<main.PingResult>;

export function RunValidationSuite():Promise<main.ValidationResult>;

export function ScoreLeague():Promise<main.ScoreLeagueResult>;

export function ScoreRookies():Promise<main.RookiesResult>;

export function SetParam(arg1:string,arg2:number):Promise<main.SetParamResult>;
