// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetParams():Promise<main.ParamsResult>;

export function Ping():Promise<main.PingResult>;

export function RunValidationSuite():Promise<main.ValidationResult>;

export function ScoreRookies():Promise<main.RookiesResult>;

export function SetParam(arg1:string,arg2:number):Promise<main.SetParamResult>;
