// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function ExecuteTransaction(arg1:main.TransactionRequest):Promise<main.TransactionResult>;

export function GetCalendarEvents():Promise<main.CalendarEventsResult>;

export function GetCurrentPhase():Promise<main.PhaseResult>;

export function GetFeed():Promise<main.FeedResult>;

export function GetFranchiseState(arg1:string):Promise<main.FranchiseStateResult>;

export function GetFranchises():Promise<main.FranchisesResult>;

export function GetFreeAgentPool():Promise<main.FreeAgentPoolResult>;

export function GetFreeAgents():Promise<main.FreeAgentsResult>;

export function GetLeagueSchedule():Promise<main.LeagueScheduleResult>;

export function GetLeagueSetting(arg1:string):Promise<main.LeagueSettingResult>;

export function GetLegalOps():Promise<main.LegalOpsResult>;

export function GetParams():Promise<main.ParamsResult>;

export function GetPlayerScore(arg1:string):Promise<main.PlayerScoreResult>;

export function GetPowerRankings(arg1:number,arg2:string):Promise<main.PowerRankingsResult>;

export function GetRankings():Promise<main.RankingsResult>;

export function GetRoster(arg1:string):Promise<main.RosterResult>;

export function Ping():Promise<main.PingResult>;

export function PreviewTransaction(arg1:main.TransactionRequest):Promise<main.TransactionResult>;

export function RunValidationSuite():Promise<main.ValidationResult>;

export function ScoreLeague():Promise<main.ScoreLeagueResult>;

export function ScoreRookies():Promise<main.RookiesResult>;

export function SetLeagueSettingOverride(arg1:string,arg2:string,arg3:string):Promise<main.SetLeagueSettingResult>;

export function SetParam(arg1:string,arg2:number):Promise<main.SetParamResult>;
