// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetParams() {
  return window['go']['main']['App']['GetParams']();
}

export function GetRankings() {
  return window['go']['main']['App']['GetRankings']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function RunValidationSuite() {
  return window['go']['main']['App']['RunValidationSuite']();
}

export function ScoreLeague() {
  return window['go']['main']['App']['ScoreLeague']();
}

export function ScoreRookies() {
  return window['go']['main']['App']['ScoreRookies']();
}

export function SetParam(arg1, arg2) {
  return window['go']['main']['App']['SetParam'](arg1, arg2);
}
